name: 🤖 Build & run tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    name: Build & run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build
